force-app/main/default/objects/Error_Log__c/fields/Log_date__c.field-meta.xml
<CustomField>
    <fullName>Log_date__c</fullName>
    <description>Store the Date &amp; Time details when the Error Occurred</description>
    <inlineHelpText>Date &amp; Time details when the Error Occurred</inlineHelpText>
    <label>Log date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>Stores the Complete Stack Track about the Problem</description>
    <inlineHelpText>Complete track of problem</inlineHelpText>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <inlineHelpText>Name of Apex</inlineHelpText>
    <label>Process Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/mfclasstest.cls
@istest
public class mfclasstest {
    public static testmethod void InsertErrorLog(){
       String LogDetails='Semicolon is missing.', Processname='Syntax Error';
       Test.startTest();
       Id errorId= mfclass.InsertErrorLog(Processname, LogDetails);
       Test.stopTest();
       List<Error_Log__c> ob=[SELECT Id, Name, Log_date__c,Log_Details__c,Process_Name__c from Error_Log__c where Id=: errorId ];

       System.assertEquals(1, ob.size());
       System.assertEquals(Datetime.now(), ob[0].Log_Date__c);
        System.assertEquals(LogDetails, ob[0].Log_Details__c);
        System.assertEquals(Processname, ob[0].Process_Name__c);
    }
}