main/default/objects/Event_Detail__c/Event_Detail__c.object-meta.xml
<CustomObject>
    <label>Event Detail</label>
    <nameField>
        <displayFormat>e-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Detail__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>End date of event</description>
    <inlineHelpText>Enter ending date of event</inlineHelpText>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Starting date of event</description>
    <inlineHelpText>Start Date</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Details of event for speaker&apos;s end</description>
    <inlineHelpText>details for speaker</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event_Detail__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>Speaker details master detail</description>
    <inlineHelpText>Details for speaker&apos;s event</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/ESclass.cls
public class ESclass {
    public static void insertEventSpeaker(List<Event_Speaker__c> lst){
        List<Id> speakerIds = new List<Id>();  
        Map<Id,DateTime> requested_bookings = new Map<Id,DateTime>();
       for(Event_Speaker__c esc:lst){
           requested_bookings.put(esc.Event__c,null);
           speakerIds.add(esc.Speaker__c);
       }  
       List<Event_Detail__c> relatedEvents=[Select Id,Start__c,End__c from Event_Detail__c where Id in :requested_bookings.keySet()];
       for(Event_Detail__c related_event : relatedEvents) {
        requested_bookings.put(related_event.Id,related_event.Start__c);
       }
       List<Event_Speaker__c> related_speakers = [SELECT ID, Speaker__c, Event__c, Event__r.Start__c,Event__r.End__c from Event_Speaker__c WHERE Speaker__c IN :speakerIds];
    for(Event_Speaker__c esc:lst){
        Datetime bookingtime=requested_bookings.get(esc.Event__c);
        for(Event_Speaker__c speaker:related_speakers){
            if(speaker.Speaker__c==esc.Speaker__c && speaker.Event__r.Start__c<=bookingtime && speaker.Event__r.End__c>=bookingtime ){
                esc.addError('Duplicate booking found');
            }
        }
    }
    }
}