main/default/objects/Event_Detail__c/Event_Detail__c.object-meta.xml
<CustomObject>
    <label>Event Detail</label>
    <nameField>
        <displayFormat>e-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Detail__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>End date of event</description>
    <inlineHelpText>Enter ending date of event</inlineHelpText>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Mode of event</description>
    <inlineHelpText>Mode of event</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event_Detail__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Event is live or not</description>
    <inlineHelpText>Whether event is live or not ?</inlineHelpText>
    <label>Live ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Maximum seats in event</description>
    <externalId>true</externalId>
    <inlineHelpText>Limited Seats</inlineHelpText>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Event_Detail__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Event</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the name of the event.</inlineHelpText>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Recurring__c.field-meta.xml
<CustomField>
    <fullName>Recurring__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Event will repeat or not</description>
    <inlineHelpText>Attending the event 2nd time ?</inlineHelpText>
    <label>Recurring ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Starting date of event</description>
    <inlineHelpText>Start Date</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Details of event for speaker&apos;s end</description>
    <inlineHelpText>details for speaker</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event_Detail__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>Speaker details master detail</description>
    <inlineHelpText>Details for speaker&apos;s event</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ESclassTest.cls
@isTest
private class ESclassTest {
    @TestSetup static void duplicateSpeakerTest(){
        Event_Detail__c event1=new Event_Detail__c(
            Name__c='Singing Comp 2',
            Start__c=System.now(),
            End__c=System.now().addDays(3),
            Event_Type__c='Virtual',
            Frequency__c='Daily',
            Live__c=true,
            Recurring__c=true,
            Max_Seats__c=100
        );
        insert event1;
        Event_Detail__c event2=new  Event_Detail__c(
            Name__c='Singing Comp 2',
            Start__c=System.now(),
            End__c=System.now().addDays(3),
            Event_Type__c='Virtual',
            Frequency__c='Daily',
            Live__c=true,
            Recurring__c=true,
            Max_Seats__c=100
        );
        insert event2;
        Speaker__c speaker=new Speaker__c(
            Name='Nirvana'
        );
        insert speaker;
        try{
            Event_Speaker__c es1=new Event_Speaker__c(Event__c=event1.Id,Speaker__c=speaker.Id);
            insert es1;
            Event_Speaker__c es2=new Event_Speaker__c(Event__c=event2.Id,Speaker__c=speaker.Id);
            insert es2;
        }
        catch(Exception e){
            System.debug(e.getMessage());
        }
    }
    @isTest static void testDuplicateRecord(){
        Test.startTest();
        try{
            List<Event_Speaker__c> lst1=[Select Id,Event__c,Speaker__c from Event_Speaker__c where Event__r.Name__c='Singing Competetion 1'];
             ESclass.insertEventSpeaker(lst1);
            List<Event_Speaker__c> lst2=[Select Id,Event__c,Speaker__c from Event_Speaker__c where Event__r.Name__c='Singing Competetion 2'];
             ESclass.insertEventSpeaker(lst2);
        }
        catch(Exception e){
            Boolean checkError=e.getMessage().contains('Duplicate booking found') ? true : false;
            System.AssertEquals(checkError, true);
        }
        Test.stopTest();
    }
}