main/default/objects/Event_Detail__c/Event_Detail__c.object-meta.xml
<CustomObject>
    <label>Event Detail</label>
    <nameField>
        <displayFormat>e-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Detail__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>End date of event</description>
    <inlineHelpText>Enter ending date of event</inlineHelpText>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Mode of event</description>
    <inlineHelpText>Mode of event</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event_Detail__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Event is live or not</description>
    <inlineHelpText>Whether event is live or not ?</inlineHelpText>
    <label>Live ?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Event_Detail__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Event</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the name of the event.</inlineHelpText>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Recurring__c.field-meta.xml
<CustomField>
    <fullName>Recurring__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Event will repeat or not</description>
    <inlineHelpText>Attending the event 2nd time ?</inlineHelpText>
    <label>Recurring ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Starting date of event</description>
    <inlineHelpText>Start Date</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/oldrecordsTest.cls
@isTest
private class oldrecordsTest {
    @TestSetup static void insertMethod(){
        List<Event_Detail__c> eventList=new List<Event_Detail__c>();
        for(integer i=0;i<200;i++){
            Event_Detail__c ec=new Event_Detail__c();
            ec.Name__c='Event Function'+i;
            ec.Start__c=Date.parse('14/01/2023');
            ec.End__c=Date.parse('16/01/2023');
            ec.Event_Type__c='Virtual';
            ec.Frequency__c='Daily';
            ec.Live__c=true;
            ec.Recurring__c=true;
            eventList.add(ec);
        }
        insert eventList;
    }
    @isTest static void testInsertMethod(){
        Test.startTest();
        oldrecords eBatch=new oldrecords();
        Database.executeBatch(eBatch);
        Test.stopTest();
        List<Event_Detail__c> deletEventsRecord = [Select Id,Name__c from Event_Detail__c];
        System.assertEquals(0, deletEventsRecord.size(),'All records before 2 months should be deleted.');
    }
}