main/default/objects/Event_Detail__c/Event_Detail__c.object-meta.xml
<CustomObject>
    <label>Event Detail</label>
    <nameField>
        <displayFormat>e-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Detail__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Maximum seats in event</description>
    <externalId>true</externalId>
    <inlineHelpText>Limited Seats</inlineHelpText>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Event_Detail__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Event</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the name of the event.</inlineHelpText>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of organizer</description>
    <inlineHelpText>Organizer Name</inlineHelpText>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Starting date of event</description>
    <inlineHelpText>Start Date</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

main/default/objects/Event_Organizer__c/fields/E_mail__c.field-meta.xml
<CustomField>
    <fullName>E_mail__c</fullName>
    <description>Email of user</description>
    <inlineHelpText>Enter Valid E-mail.</inlineHelpText>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

main/default/classes/EventWebService.cls
@RestResource(urlMapping='/EventDetails/*')
global with sharing class EventWebService {
 @HttpGet
  //global static Event_Detail__c doGet(){
   // RestRequest req= RestContext.request;
    //RestResponse res= RestContext.response;
    //String AccNumber = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);

    global static list<Event_Detail__c> getEventMethod(){

    list<Event_Detail__c> allevents=[select Id,Name__c,Start__c, Max_Seats__c,Organizer__r.name, Organizer__r.E_mail__c from Event_Detail__c];
   return allevents;
    }
  }