main/default/objects/Event_Detail__c/Event_Detail__c.object-meta.xml
<CustomObject>
    <label>Event Detail</label>
    <nameField>
        <displayFormat>e-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Detail__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>End date of event</description>
    <inlineHelpText>Enter ending date of event</inlineHelpText>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

main/default/objects/Event_Detail__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Event is live or not</description>
    <inlineHelpText>Whether event is live or not ?</inlineHelpText>
    <label>Live ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/oldrecords.cls
public class oldrecords implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, Name from Event_Detail__c where End__c <= LAST_N_MONTHS:2 AND Live__c=true]);
    }
    public void  execute(Database.BatchableContext BC,List<sObject> scope){
        delete scope;
   }
   public void finish(Database.BatchableContext BC){
    AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    String[] toAddresses = new String[] {a.CreatedBy.Email};
    mail.setToAddresses(toAddresses);
    mail.setSubject('Apex Job Status:- ' + a.Status);
    mail.setPlainTextBody ('The batch Apex job processed');
    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
 }
}