main/default/objects/Event_Detail__c/Event_Detail__c.object-meta.xml
<CustomObject>
    <label>Event Detail</label>
    <nameField>
        <displayFormat>e-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Detail__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Mode of event</description>
    <inlineHelpText>Mode of event</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Locations__c.field-meta.xml
<CustomField>
    <fullName>Locations__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location look up field</description>
    <inlineHelpText>Location of event</inlineHelpText>
    <label>Locations</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of organizer</description>
    <inlineHelpText>Organizer Name</inlineHelpText>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location adress book</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

main/default/classes/NewRegistration.cls
public class NewRegistration{
    public Event_Organizer__c esobj{get;set;}
    public Event_Detail__c ed{get;set;}
    public Location_Address_Book__c locobj{get;set;}
    
    public NewRegistration() {
        esobj = new Event_Organizer__c();
        ed = new Event_Detail__c();
        locobj= new Location_Address_Book__c();
      
    } 
    public void addDetailsEO(){
        Savepoint sp = Database.setSavepoint();
        try{
             if(ed.Event_Type__c!='Virtual'){
                
              ed.Locations__c= locobj.Id;
              
                insert locobj;
             //ed.Locations__c=locobj.Name;
                  
            }
            
            insert esobj;
            ed.Organizer__c= esobj.Id;
           ed.Locations__c= locobj.Id;
        //  ed.Locations__c='Virtual Event';
            
        //    insert ed;  
           
         insert ed; 
         esobj = new Event_Organizer__c();
        ed = new Event_Detail__c();
        locobj= new Location_Address_Book__c();

        }
        catch(Exception e){
            System.debug(e.getMessage());
          Database.rollback(sp);
        }
    }

}