main/default/objects/Event_Detail__c/Event_Detail__c.object-meta.xml
<CustomObject>
    <label>Event Detail</label>
    <nameField>
        <displayFormat>e-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Detail__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>End date of event</description>
    <inlineHelpText>Enter ending date of event</inlineHelpText>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Maximum seats in event</description>
    <externalId>true</externalId>
    <inlineHelpText>Limited Seats</inlineHelpText>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Event_Detail__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Event</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the name of the event.</inlineHelpText>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of organizer</description>
    <inlineHelpText>Organizer Name</inlineHelpText>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Starting date of event</description>
    <inlineHelpText>Start Date</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

main/default/objects/Event_Organizer__c/fields/E_mail__c.field-meta.xml
<CustomField>
    <fullName>E_mail__c</fullName>
    <description>Email of user</description>
    <inlineHelpText>Enter Valid E-mail.</inlineHelpText>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

main/default/classes/EventWebServiceTest.cls
@isTest
private class EventWebServiceTest {
    @TestSetup
 static void createData(){
        
        //Organiser Details

        Event_Organizer__c organob = new Event_Organizer__c(
        Name= 'Ted Talks',E_mail__c= 'tedtalks@jhfx.com');

        insert organob;

            //Event Details

       Event_Detail__c eventob= new Event_Detail__c(
        Name__c='The rock',
        Start__c=System.now(),
        End__c=System.now().addDays(10),Max_Seats__c=10,
        Organizer__c=organob.Id
        );
    insert eventob;
    }

    @isTest
    static void eventWebServiceTest(){
    RestRequest request = new RestRequest();
    request.requestURI='https://mirketa24-dev-ed.develop.lightning.force.com/services/apexrest/EventDetails';
    request.httpMethod= 'GET';
    RestContext.request= request;

    Event_Detail__c eventdata= [Select Id,Name__c,Start__c, Max_Seats__c,Organizer__r.name, Organizer__r.E_mail__c from Event_Detail__c];
    
    List<Event_Detail__c> responselist= EventWebService.getEventMethod();
    Event_Detail__c response = responselist.get(0);
    
    System.assert(responselist != null);
    System.assertEquals(eventdata.id, response.id);
    System.assertEquals(eventdata.Start__c, response.Start__c);
    System.assertEquals(eventdata.Max_Seats__c, response.Max_Seats__c);
    System.assertEquals(eventdata.Organizer__r.Name, response.Organizer__r.Name);
    
    
    }
}