main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>email of attendee</description>
    <inlineHelpText>Enter attendee&apos;s email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

main/default/objects/Attendee__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Attendee&apos;s phone number</description>
    <inlineHelpText>Enter attendee&apos;s phone number</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <description>Attendee of the event master detail</description>
    <inlineHelpText>Details of Attendee</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Details of event master detail</description>
    <inlineHelpText>Details of event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event_Detail__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Event_Detail__c/Event_Detail__c.object-meta.xml
<CustomObject>
    <label>Event Detail</label>
    <nameField>
        <displayFormat>e-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Detail__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>End date of event</description>
    <inlineHelpText>Enter ending date of event</inlineHelpText>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Mode of event</description>
    <inlineHelpText>Mode of event</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event_Detail__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Event is live or not</description>
    <inlineHelpText>Whether event is live or not ?</inlineHelpText>
    <label>Live ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Maximum seats in event</description>
    <externalId>true</externalId>
    <inlineHelpText>Limited Seats</inlineHelpText>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Event_Detail__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Event</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the name of the event.</inlineHelpText>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Recurring__c.field-meta.xml
<CustomField>
    <fullName>Recurring__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Event will repeat or not</description>
    <inlineHelpText>Attending the event 2nd time ?</inlineHelpText>
    <label>Recurring ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Starting date of event</description>
    <inlineHelpText>Start Date</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

main/default/objects/Event_Organizer__c/fields/E_mail__c.field-meta.xml
<CustomField>
    <fullName>E_mail__c</fullName>
    <description>Email of user</description>
    <inlineHelpText>Enter Valid E-mail.</inlineHelpText>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone Number of user</description>
    <inlineHelpText>Enter your phone number without country code.</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/sendEmailTest.cls
@isTest
public class sendEmailTest {
    @TestSetup static void makeData(){
        Event_Organizer__c eoc=new Event_Organizer__c(
            Name='Pallavi Verma',
            E_mail__c='pallavi.verma@mirketa.com',
            Phone__c='67856476'
        );
        
        insert eoc;

        Event_Detail__c ec=new Event_Detail__c(
            Name__c='Dancing Competetion',
            Start__c=System.now(),
            End__c=System.now().addDays(3),
            Event_Type__c='Virtual',
            Frequency__c='Daily',
            Live__c=true,
            Recurring__c=true,
            Max_Seats__c=10
        );
        insert ec;
        Attendee__c at=new Attendee__c(
            Name='harshil',
            Email__c='pallavi.1923cs1189@kiet.edu',
            Phone__c='9869543210'
        );
        insert at;
        Event_Attendee__c evtAtt = new Event_Attendee__c(Event__c = ec.Id, Attendee__c = at.Id);
        insert evtAtt;
    }
    @isTest static void testEventAttendee(){
        Test.startTest();
        List<Event_Attendee__c> eat=[Select Id,Event__c,Attendee__c from Event_Attendee__c where Event__r.Name__c='Dancing Competetion'];
        sendEmailClass.insertEventAttendee(eat);
        Integer invoc=Limits.getEmailInvocations();
        System.assertEquals(1, invoc,'An email should be sent to the sender');
        Test.stopTest();
    }
}