main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>email of attendee</description>
    <inlineHelpText>Enter attendee&apos;s email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

main/default/objects/Attendee__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Attendee&apos;s phone number</description>
    <inlineHelpText>Enter attendee&apos;s phone number</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <description>Attendee of the event master detail</description>
    <inlineHelpText>Details of Attendee</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Details of event master detail</description>
    <inlineHelpText>Details of event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event_Detail__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Event_Detail__c/Event_Detail__c.object-meta.xml
<CustomObject>
    <label>Event Detail</label>
    <nameField>
        <displayFormat>e-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Detail__c/fields/Locations__c.field-meta.xml
<CustomField>
    <fullName>Locations__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location look up field</description>
    <inlineHelpText>Location of event</inlineHelpText>
    <label>Locations</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Detail__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Event</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the name of the event.</inlineHelpText>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of organizer</description>
    <inlineHelpText>Organizer Name</inlineHelpText>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Detail__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Starting date of event</description>
    <inlineHelpText>Start Date</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone Number of user</description>
    <inlineHelpText>Enter your phone number without country code.</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location adress book</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Address_Book__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Name of city</description>
    <inlineHelpText>Name of city</inlineHelpText>
    <label>City</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Postal Code of the residence.</description>
    <inlineHelpText>Enter the postal code</inlineHelpText>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Residing state</description>
    <externalId>true</externalId>
    <inlineHelpText>Residing state</inlineHelpText>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Name of street</description>
    <externalId>true</externalId>
    <inlineHelpText>Name of street</inlineHelpText>
    <label>Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/sendEmailClass.cls
public class sendEmailClass {

   public static void insertEventAttendee(List<Event_Attendee__c> lst){
    set<Id> attendeeId= new set<Id>();
    set<Id> eventId= new set<Id>();
    List<Messaging.SingleEmailMessage> mails=new List<Messaging.SingleEmailMessage>();
    for(Event_Attendee__c ealist: lst){
        if(ealist.Attendee__c!=null){
            attendeeId.add(ealist.Attendee__c);
        }
        if(ealist.Event__c!=null){
            eventId.add(ealist.Event__c);
        }
        Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
        Attendee__c ob1= [SELECT Name, Email__c, Phone__c from Attendee__c where Id in :attendeeId];
        Event_Detail__c ob2 = [SELECT Name__c, Organizer__r.Name, Locations__r.Street__c, Locations__r.City__c,Locations__r.State__c,Locations__r.Postal_Code__c, Start__c from Event_Detail__c where Id in : eventId];
        List<String> toAddress = new List<String>();
        toAddress.add(ob1.Email__c);
        mail.setToAddresses(toAddress);
        mail.setSenderDisplayName(ob2.Organizer__r.Name);

    String subject = 'Pass for the'+ ob2.Name__c;
    mail.setSubject(subject);
    String body = 'Dear '+ ob1.Name+', ';
    body += 'Thank you for registering for '+ob2.Name__c+'which will be Organized on ';
    body += ob2.Start__c + '& will be held in '+ ob2.Locations__r.Street__c+ ', ' + ob2.Locations__r.City__c+ '.';
    body+= 'We are excited to have you, see you at the event.<br>';
    body+='Thanks<br>';
    body+=ob2.Organizer__r.Name;
    mail.setHtmlBody(body);
    mails.add(mail);
    
    }
     
    Messaging.sendEmail(mails);  
}
}