main/default/objects/Attendee__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location of the attendee</description>
    <inlineHelpText>Attendee&apos;s current address</inlineHelpText>
    <label>Location_Address_Book</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <description>Attendee of the event master detail</description>
    <inlineHelpText>Details of Attendee</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location adress book</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeRegistrationController.cls
public class AttendeeRegistrationController {
 public Attendee__c attendob{get;set;}
 public Event_Attendee__c eattendob{get;set;}
 public Location_Address_Book__c locob{get;set;}
 public AttendeeRegistrationController (){
 
 attendob= new Attendee__c();
 eattendob= new Event_Attendee__c ();
 locob= new Location_Address_Book__c();
 

}
 public void addAttendeeDetails(){
      Savepoint sp = Database.setSavepoint();
  try{
    insert locob;
    attendob.Location_Address_Book__c= locob.Id;
  locob.Name= attendob.Location_Address_Book__c;
  
  insert attendob;
  eattendob.Attendee__c= attendob.Id;
  eattendob.Name= attendob.Name;
  
  
  insert eattendob;

  attendob= new Attendee__c();
 eattendob= new Event_Attendee__c ();
 locob= new Location_Address_Book__c();

  
  }
  catch(Exception e){
  System.debug(e.getMessage());
      Database.rollback(sp);
  }
  }
 }