force-app/main/default/objects/Speaker__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Speaker&apos;s company</description>
    <inlineHelpText>Speaker&apos;s company</inlineHelpText>
    <label>Company</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/E_mail__c.field-meta.xml
<CustomField>
    <fullName>E_mail__c</fullName>
    <description>Email of speaker</description>
    <externalId>true</externalId>
    <inlineHelpText>Speaker&apos;s mail id</inlineHelpText>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Speaker&apos;s Phone number</description>
    <inlineHelpText>Speaker&apos;s Phone number</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/createSpeakerRecord.cls
@RestResource(urlMapping='/createSpeaker/*')
global with sharing class createSpeakerRecord {
    @HttpPost
    global static String doPost(String name, String email, String phone, String company) {
        Speaker__c speakerob = new Speaker__c();
        speakerob.Name= name;
        speakerob.Phone__c= phone;
        speakerob.E_mail__c=email;
        speakerob.Company__c=company; 

        try{
            RestResponse res = RestContext.response;
            res.statusCode=200;
            insert speakerob;
            System.debug('speakerob: '+speakerob);
            return 'Success';
            
    }
    catch(Exception e){
         RestResponse res = RestContext.response;
        res.statusCode= 400;
        return  'Failed';

    }
}
}