force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>Speaker details master detail</description>
    <inlineHelpText>Details for speaker&apos;s event</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SpeakerRegistrationController.cls
public class SpeakerRegistrationController {
    public Speaker__c speakerob{get;set;}
    public Event_Speaker__c espeakerob {get;set;}
    
    public SpeakerRegistrationController(){
        speakerob = new Speaker__c();
        espeakerob = new Event_Speaker__c();
    }
    public void addspeakerDetails(){
    //    Savepoint sp = Database.setSavepoint();
        try{
           
            insert speakerob;
            System.debug('Speaker Ob='+ speakerob);
             
           // insert espeakerob;
            espeakerob.Speaker__c=speakerob.Id;
            System.debug('Speaker Id='+ speakerob.Id);
            insert espeakerob;
            System.debug('Event Speaker Id='+ espeakerob);
            speakerob = new Speaker__c();
      //  espeakerob = new Event_Speaker__c();
           
        }
        catch(Exception e){
            System.debug(e.getMessage());
          //  Database.rollback(sp);
        }
    }

}